#theme: jekyll-theme-gitbook
theme: just-the-docs

# Configurations
title:            CP Lang
longtitle:        CP Language
author:           Carlos E. B. Machado
email:            carlosebmachado@outlook.com
description: >
  CP Language website.

# customize the link favicon in header, will be {{site.baseurl}}/{{site.favicon_path}}
favicon_path:     favicon.png
